version: '1'
services:
  springboot-app:
    container_name: apica
    image: apica
    restart: always
    build: .
    ports: 
      - 8100:8100
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
  
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3320:3306
    environment:
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: root