/*
 * This file is generated by jOOQ.
 */
package com.jooq.apica;


import com.jooq.apica.tables.User;
import com.jooq.apica.tables.UserJournal;
import com.jooq.apica.tables.records.UserJournalRecord;
import com.jooq.apica.tables.records.UserRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * user_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserJournalRecord> KEY_USER_JOURNAL_PRIMARY = Internal.createUniqueKey(UserJournal.USER_JOURNAL, DSL.name("KEY_user_journal_PRIMARY"), new TableField[] { UserJournal.USER_JOURNAL.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserJournalRecord, UserRecord> FK_USERID = Internal.createForeignKey(UserJournal.USER_JOURNAL, DSL.name("fk_userId"), new TableField[] { UserJournal.USER_JOURNAL.USERID }, Keys.KEY_USER_PRIMARY, new TableField[] { User.USER.ID }, true);
}
