/*
 * This file is generated by jOOQ.
 */
package com.jooq.apica;


import com.jooq.apica.tables.User;
import com.jooq.apica.tables.UserJournal;


/**
 * Convenience access to all tables in user_db.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>user_db.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>user_db.user_journal</code>.
     */
    public static final UserJournal USER_JOURNAL = UserJournal.USER_JOURNAL;
}
