/*
 * This file is generated by jOOQ.
 */
package com.jooq.apica;


import com.jooq.apica.tables.User;
import com.jooq.apica.tables.UserJournal;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_db</code>
     */
    public static final UserDb USER_DB = new UserDb();

    /**
     * The table <code>user_db.user</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>user_db.user_journal</code>.
     */
    public final UserJournal USER_JOURNAL = UserJournal.USER_JOURNAL;

    /**
     * No further instances allowed
     */
    private UserDb() {
        super("user_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            User.USER,
            UserJournal.USER_JOURNAL
        );
    }
}
